<H2> 1. Basics

In [1]:
# Basic numeric operation in python
fare = 240
ticket = 6
total_cost = fare*ticket
total_cost

1440

In [1]:
# Type of any variable
height = 5.11
print(type(height))

day_of_week = 5
print(type(day_of_week))

message = 'Hello world its rohan learning data science with python'
print(type(message))

z = False
print(type(z))

a = [2,3,42,44]
print(type(a))

<class 'float'>
<class 'int'>
<class 'str'>
<class 'bool'>
<class 'list'>


In [5]:
# Behaviour with different types
print(2+3)
print('abc' + 'xyz')
print([1,3,9] + [10,7,1])
print(True + False)
print(True + True)
print(False + False)

5
abcxyz
[1, 3, 9, 10, 7, 1]
1
2
0


<H2> 2. Functions and Packages

In [1]:
# Basic functions :

# Max function
fam_height = [1.73, 2.67, 1.414, 2.44]
print(max(fam_height))

# Round funtion
print(round(1.84999,1))
print(round(1.84999,2))
print(round(26.34,-1))
print(round(26.34))     # By default it round offs to a 0 digits and returns a interger value

2.67
1.8
1.85
30.0
26


In [17]:
# Using help funcion in python to get the idea of round funtion
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [5]:
# Methods in python
# Methods are functions that belong to a particular object 
name = 'rohan'
print(type(name))
print(name.capitalize())
print(name.upper())
print(name.replace('an','it'))
# here "name" is the "str" object having methods like capitalize(), upper(), replace()

age = 23.3
print(type(age))
#print(age.bit_length(2))

fam = ['Rohan', 23.3,'Rohit',21.2,'Aniket',30.3,21.2]
print(type(fam))
print(fam.index('Rohan'))    # Index tells the position of 'Rohan' in list
print(fam.count(21.2))       # Count tells how many times 21.2 has occured
print(fam.index('Aniket'))
# here "age" is the "float" object having methods like  bit_length(), count(), index(), append()

fam.append('DadaJi Naroji')
print(fam)
fam.append(56)
print(fam)
# here "fam" is the "list" object haing methods like append()

<class 'str'>
Rohan
ROHAN
rohit
<class 'float'>
<class 'list'>
0
2
4
['Rohan', 23.3, 'Rohit', 21.2, 'Aniket', 30.3, 21.2, 'DadaJi Naroji']
['Rohan', 23.3, 'Rohit', 21.2, 'Aniket', 30.3, 21.2, 'DadaJi Naroji', 56]


In [61]:
# Packages in python 
# python has a lot of packages widely distributed making it easier to perform various operations
# each package has its own methods and functions associated with them
# numpy, pandas, scikit-learn

import numpy
array([1,2,3])

NameError: name 'array' is not defined

In [62]:
import numpy
numpy.array([1,2,3])   # assigning it properly like numpy.array

array([1, 2, 3])

In [77]:
from numpy import array
array[1,2,3])

TypeError: 'builtin_function_or_method' object is not subscriptable

In [14]:
# unclear way of importing from numpy
from numpy import array
fam = ['Rohan', 23.3,'Rohit',21.2,'Aniket',30.3,21.2]


need to continue from part 2 last 2 slides of intro to python


SyntaxError: invalid syntax (<ipython-input-14-7da264d420ae>, line 6)

<h2> 3. Lists

In [45]:
# Python list
# list can contain any kind of object like float, string etc 
# list are used when we need to store multiple values
fam1 = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]
print(fam1)
print(type(fam1))

#list of list 
fam2 = [['liz',1.73],['emma',1.68],['mom,1.71'],['dad',1.89]]
print(fam2)

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]
<class 'list'>
[['liz', 1.73], ['emma', 1.68], ['mom,1.71'], ['dad', 1.89]]


In [3]:
# Subsetting a list
# it always starts with 0 index like an array
print(fam1[2])
print(fam2[2])

print(fam1[-1])
print(fam2[-4])

emma
['mom,1.71']
1.89
['liz', 1.73]


In [10]:
fam2 = [['liz',1.73],['emma',1.68],['mom,1.71'],['dad',1.89]]
# list slicing [inclusive : exclusive : steps]
print(fam2)
# complete list selected 
print(fam2[:])
# except first and last  all other are selected
print(fam2[1:3])
print(fam2[:4])
# only first value selected
print(fam2[0:1])

# Slicing of list in steps of 2 
print(fam2[::2])

[['liz', 1.73], ['emma', 1.68], ['mom,1.71'], ['dad', 1.89]]
[['liz', 1.73], ['emma', 1.68], ['mom,1.71'], ['dad', 1.89]]
[['emma', 1.68], ['mom,1.71']]
[['liz', 1.73], ['emma', 1.68], ['mom,1.71'], ['dad', 1.89]]
[['liz', 1.73]]
[['liz', 1.73], ['mom,1.71']]


In [8]:
# List manipulation
fam_uk = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]

#changing value of list using indexing
fam_uk[7] = 1.86
print(fam_uk)

#changing value of list using slicing
fam_uk[:2] = ["lisa",1.74]
print(fam_uk)

fam_uk_ext = fam_uk + ["me",1.79]
print(fam_uk_ext)

#removing value from list using indexing
del(fam_uk[2])
print(fam_uk)

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86]
['lisa', 1.74, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86]
['lisa', 1.74, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86, 'me', 1.79]
['lisa', 1.74, 1.68, 'mom', 1.71, 'dad', 1.86]


In [36]:
# Behind the scene of list manipulation
x = ['a','b','c']
y = x
y[1] = 'z'
print(y)
print(x)
# Here we see that both y and x have become same 

['a', 'z', 'c']
['a', 'z', 'c']


In [4]:
x = ['a','b','c']
y = list(x)
y = x[:]
y[1] = 'z'
print(x)
print(y)
# By using list() we got different values for both x and y list although y has been created using x

['a', 'b', 'c']
['a', 'z', 'c']


In [5]:
# Numpy : Numeric Python , similar to list but unlike list it can be used for numeric calculations
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
bmi = weight/height**2
print(bmi)
# List can not be used to perform numeric operations

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [9]:
# To perform numeric operation using list we convert them into numpy array
import numpy as np
np_height = np.array(height)
np_weight = np.array(weight)
bmi=np_weight/np_height**2
print(type(bmi))
print(bmi)
# It performs element-wise operation 
65.4/1.73**2

<class 'numpy.ndarray'>
[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]


21.85171572722109

In [44]:
# Numpy accepts only one type of value unlike list which can contain any type of value
np.array(1.0,"is",True)

ValueError: only 2 non-keyword arguments accepted

In [5]:
# Different types have differet behaviour
# Lists are concated but numpy arrays are added 
import numpy as np
list = [1,2,3]
print(list+list)

numpy_array = np.array([1,2,3])
print(numpy_array+numpy_array)

[1, 2, 3, 1, 2, 3]
[2 4 6]


<h2> 4. Numpy

In [17]:
# Like list Numpy can also be indexed
print(bmi)
print(bmi[1])
print(bmi>23)
print(bmi[bmi>23])
bmi.shape

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]
20.97505668934241
[False False False  True False]
[24.7473475]


(5,)

In [46]:
# 2-D Numpy array
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],[65.4, 59.2, 63.6, 88.4, 68.7]])
print(np_2d)
print(type(np_2d))

# If you convert one element in an array to string all other will also be converted into string as shown below
np_2d_stringType = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],[65.4, 59.2, 63.6, 88.4, "68.7"]])
print(np_2d_stringType)
print(type(np_2d_stringType))

np_2d.shape

[[ 1.73  1.68  1.71  1.89  1.79]
 [65.4  59.2  63.6  88.4  68.7 ]]
<class 'numpy.ndarray'>
[['1.73' '1.68' '1.71' '1.89' '1.79']
 ['65.4' '59.2' '63.6' '88.4' '68.7']]
<class 'numpy.ndarray'>


(2, 5)

In [33]:
# Subsetting of an array 
# [1.73, 1.68, 1.71, 1.89, 1.79]
# [65.4, 59.2, 63.6, 88.4, 68.7]
print(np_2d[0])
print(np_2d_stringType[0]) 
print(np_2d[0][1])
print(np_2d[0,2])
print(np_2d[:,1:3])

[1.73 1.68 1.71 1.89 1.79]
['1.73' '1.68' '1.71' '1.89' '1.79']
1.68
1.71
[[ 1.68  1.71]
 [59.2  63.6 ]]


In [ ]:
# Basic statistics with Numpy 
# Using Numpy to perform basic mean, median , correlation 




In [64]:
# Random number generation using numpy.random
# 1-D array generation
import numpy as np
np.random.randint(low = 1, high = 10, size = 10)   #low is inclusive, high is exclusive

array([4, 1, 6, 8, 5, 7, 7, 1, 2, 5])

In [66]:
# 2-D array generation
np.random.randint(low = 5,high = 25,size = (4,5))

array([[18, 19, 11, 16,  5],
       [14,  6, 16, 12, 19],
       [10, 11, 17, 19, 14],
       [ 8, 10,  6, 22, 16]])

In [7]:
# high as inclusive
np.random.randint(0,10 + 1)   # Using 10+1 we can generate upto 10

10

In [13]:
len(np.random.randint(1,20,10))

10

In [126]:
# Random number of any shape
np.random.seed(12)
print(np.random.randn(2,3))
print(np.random.rand(2,3)-10)
print(np.random.random(10))  # random array creation using np.random.random

[[ 0.47298583 -0.68142588  0.2424395 ]
 [-1.70073563  0.75314283 -1.53472134]]
[[-9.05577486 -9.14726446 -9.99774077]
 [-9.47877397 -9.44796237 -9.51462259]]
[0.76813415 0.16071675 0.76456045 0.0208098  0.13521018 0.11627302
 0.30989758 0.67145265 0.47122978 0.8161683 ]
